### PR TITLE
Add occupancy information

### PR DESCRIPTION
**Pull request by danielvillalbamota**
Add some occupancy attributes for some systems that do not manage available spots but occupied ones.

-   `occupiedSpotNumber` : Number of spots occupied.
-   `occupancyModified` : Timestamp when the `occupiedSpotNumber` was updated. The format follows the ISO8601.
-   `percentageOccupancy` : Percentage of occupied spots over the total.

### CODE REVIEW

**Comment by albertoabellagarcia** [comment]
As stated in [the guidelines](https://github.com/smart-data-models/data-models/blob/master/guidelines.md#relative-values) all the values which are relative it should be expressed in a value between 0 and 1. 
The rest of the changes looks nice. Fix it to be accepted.

**Comment by danielvillalbamota** [comment]
Ok, is there a naming convention for this kind of relatives values? I have seen some attributes with the suffix "Level" (e.g. occupancyLevel), but I would like to find the proper one.

**Comment by albertoabellagarcia** [comment]
We have neither a recommendation nor an obligation regarding this. Maybe we should. 
What it is true is that you can use a plain name (without a level suffix) for magnitudes which are relative.
so my recommendation would be if this is a real magnitude use the plain name. It is not necessary to identify that the magnitude is a percentage in the property name.

**Comment by danielvillalbamota** [comment]
Ok, then I will leave it simple. I am going to propose "occupancy" as the relative value of occupied spots out of the total spots.

**Comment by danielvillalbamota** [comment]
I want to include two more attribute related to the number of vehicle that enter and leave the parking (vehicleEntranceCount and vehicleExitCount), Should I do it in this PR or in a new one?

**Comment by albertoabellagarcia** [comment]
mostly right. There is a minor issue on the schema, I'll fix it.

**Pull request merged**
